import { SelectOption } from "../components/form/AppSelect";

export const PREFECTURE_OPTIONS: SelectOption[] = [
  { label: "HOKKAIDO", value: "HOKKAIDO" },
  { label: "AOMORI", value: "AOMORI KEN" },
  { label: "IWATE", value: "IWATE KEN" },
  { label: "MIYAGI", value: "MIYAGI KEN" },
  { label: "AKITA", value: "AKITA KEN" },
  { label: "YAMAGATA", value: "YAMAGATA KEN" },
  { label: "FUKUSHIMA", value: "FUKUSHIMA KEN" },
  { label: "IBARAKI", value: "IBARAKI KEN" },
  { label: "TOCHIGI", value: "TOCHIGI KEN" },
  { label: "GUNMA", value: "GUNMA KEN" },
  { label: "SAITAMA", value: "SAITAMA KEN" },
  { label: "CHIBA", value: "CHIBA KEN" },
  { label: "TOKYO", value: "TOKYO TO" },
  { label: "KANAGAWA", value: "KANAGAWA KEN" },
  { label: "NIIGATA", value: "NIIGATA KEN" },
  { label: "TOYAMA", value: "TOYAMA KEN" },
  { label: "ISHIKAWA", value: "ISHIKAWA KEN" },
  { label: "FUKUI", value: "FUKUI KEN" },
  { label: "YAMANASHI", value: "YAMANASHI KEN" },
  { label: "NAGANO", value: "NAGANO KEN" },
  { label: "GIFU", value: "GIFU KEN" },
  { label: "SHIZUOKA", value: "SHIZUOKA KEN" },
  { label: "AICHI", value: "AICHI KEN" },
  { label: "MIE", value: "MIE KEN" },
  { label: "SHIGA", value: "SHIGA KEN" },
  { label: "KYOTO", value: "KYOTO FU" },
  { label: "OSAKA", value: "OSAKA FU" },
  { label: "HYOGO", value: "HYOGO KEN" },
  { label: "NARA", value: "NARA KEN" },
  { label: "WAKAYAMA", value: "WAKAYAMA KEN" },
  { label: "TOTTORI", value: "TOTTORI KEN" },
  { label: "SHIMANE", value: "SHIMANE KEN" },
  { label: "OKAYAMA", value: "OKAYAMA KEN" },
  { label: "HIROSHIMA", value: "HIROSHIMA KEN" },
  { label: "YAMAGUCHI", value: "YAMAGUCHI KEN" },
  { label: "TOKUSHIMA", value: "TOKUSHIMA KEN" },
  { label: "KAGAWA", value: "KAGAWA KEN" },
  { label: "EHIME", value: "EHIME KEN" },
  { label: "KOCHI", value: "KOCHI KEN" },
  { label: "FUKUOKA", value: "FUKUOKA KEN" },
  { label: "SAGA", value: "SAGA KEN" },
  { label: "NAGASAKI", value: "NAGASAKI KEN" },
  { label: "KUMAMOTO", value: "KUMAMOTO KEN" },
  { label: "OITA", value: "OITA KEN" },
  { label: "MIYAZAKI", value: "MIYAZAKI KEN" },
  { label: "KAGOSHIMA", value: "KAGOSHIMA KEN" },
  { label: "OKINAWA", value: "OKINAWA KEN" },
];
